DROP DATABASE MANSISTEM;
CREATE DATABASE IF NOT EXISTS MANSISTEM;
USE MANSISTEM;

CREATE TABLE PROVINCE(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) UNIQUE
);

INSERT INTO PROVINCE(name) VALUES ('San Jose');
INSERT INTO PROVINCE(name) VALUES ('Alajuela');
INSERT INTO PROVINCE(name) VALUES ('Cartago');
INSERT INTO PROVINCE(name) VALUES('Heredia');
INSERT INTO PROVINCE(name) VALUES('Guanacaste');
INSERT INTO PROVINCE(name) VALUES('Puntarenas');
INSERT INTO PROVINCE(name) VALUES('Limón');

SELECT * FROM PROVINCE; 
CREATE TABLE IF NOT EXISTS USER (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
    lastname VARCHAR(60) NOT NULL,
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(60) NOT NULL,
	role NCHAR(1) NOT NULL,
    
    idProvince INT NOT NULL,
    FOREIGN KEY (idProvince) REFERENCES PROVINCE(id)
);


select * from USER